FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the current directoryt contents into the container at /app
COPY . /app

# Make port 8080 available
EXPOSE 8080

# Define environment variable
ENV NAME World

# Run application when the container launches
CMD ["Java", "-jar", ""]
