version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      MYSQL_DATABASE: aerobank
      MYSQL_USER: root
      MYSQL_PASSWORD: Halflifer94!
      MYSQL_ROOT_PASSWORD: Halflifer94!
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: