version: '3'
services:
  backend:
    build:
      context: C:\Users\Alexander King\Documents\GitHub\AeroBankApp\AeroBankApp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: C:\Users\Alexander King\Documents\GitHub\AeroBankApp\AeroBankApp\src\main\webapps
      dockerfile: Dockerfile
    ports:
      - "3000:3000"